version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: gps-rabbitmq
    hostname: rabbitmq
    ports:
      - "5672:5672"      # AMQP port
      - "15672:15672"    # Management UI port
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin123
      RABBITMQ_DEFAULT_VHOST: /
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - gps-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: gps-sqlserver
    ports:
      - "14330:1433"
    environment:
      SA_PASSWORD: Senha123
      ACCEPT_EULA: Y
      MSSQL_PID: Express
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - gps-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P Senha123 -Q 'SELECT 1'"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  rabbitmq_data:
  sqlserver_data:

networks:
  gps-network:
    driver: bridge
